spring.application.name=SocialMediaAlmat
# ?????????? ???? SQLite ? ????? ???????
spring.datasource.url=jdbc:sqlite:./data/socialmedia2.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
server.port=8080
